name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          channel: "main"

      - name: Build Flutter Web
        run: |
          flutter pub get
          flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web/
          publish_branch: gh-pages
